name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        py: ["3.9", "3.10", "3.11"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.py }}
      - name: Install deps
        run: |
          pip install -r requirements.txt pytest pytest-qt ruff
      - name: Lint
        run: ruff check .
      - name: Run tests
        run: pytest
